"""Pantheon persona pack: founders of Christianity, Islam, and Buddhism.

This pack is **opt-in only**. The personas are not registered automatically.
You must explicitly call ``accept_disclaimer()`` first, and the call must
succeed (it raises in some regions). Then ``register()`` loads the personas
into the global ``pantheon.registry``.

Why two-step gating:

1. Religious founders are simulated by an LLM. The simulation is approximate.
   No serious religious practitioner should treat its output as authoritative.
2. Some jurisdictions regulate or restrict commentary on religious founders;
   the ``PANTHEON_REGION`` environment variable lets the pack refuse to load
   in those regions and point users at the theologian-proxy pack.
3. Each verdict that includes one of these personas is required to carry an
   automatic disclaimer that the simulation does not represent any official
   religious position.

Usage::

    import pantheon_pack_founders as ppf
    ppf.accept_disclaimer()
    ppf.register()                        # registers jesus / muhammad / buddha
    # — or, if you want corpus retrieval to actually work:
    # 1) `pantheon corpus fetch jesus muhammad buddha` from a shell
    # 2) ppf.register(with_corpus=True)
"""
from __future__ import annotations

import os
from pathlib import Path

_DISCLAIMER_ACCEPTED = False
_REGISTERED = False

# The pack itself does not embed canonical religious text. The corpus
# directories ship only `manifest.yaml` files that point at public-domain
# upstream sources. Use the `pantheon corpus fetch` CLI to materialize.
_PERSONAS_ROOT = Path(__file__).parent.parent.parent / "personas"
if not _PERSONAS_ROOT.exists():
    # When installed as a wheel, persona files are colocated.
    _PERSONAS_ROOT = Path(__file__).parent / "personas"


DISCLAIMER_TEXT = """\
You are about to load LLM-simulated personas of religious founders
(Jesus, Muhammad, the Buddha). These personas are NOT authoritative
representations of any religion or its scriptures. Outputs are
approximations generated by a language model with retrieval over
public-domain canonical text where available.

Calling accept_disclaimer() means you understand:

  • The simulation may misattribute, paraphrase, or anachronize.
  • No verdict produced with these personas should be relied on for
    religious guidance.
  • Each verdict that includes one of these personas will carry an
    automatic disclaimer to the same effect.

If you operate in a jurisdiction where commentary on religious figures
is restricted, set PANTHEON_REGION to your region code; this pack will
refuse to load and recommend the theologian-proxy pack instead.
"""


class FoundersPackUnavailable(RuntimeError):
    """Raised when the pack cannot be loaded for region/policy reasons."""


def accept_disclaimer() -> None:
    """Acknowledge the simulation caveat and clear the pack for loading.

    Raises:
        FoundersPackUnavailable: when ``PANTHEON_REGION`` is set to a value
            this pack refuses to operate in.
    """
    global _DISCLAIMER_ACCEPTED
    region = os.environ.get("PANTHEON_REGION", "").strip().lower()
    blocked_regions = {"cn"}
    if region in blocked_regions:
        raise FoundersPackUnavailable(
            f"pantheon-pack-founders refuses to load in region={region!r}. "
            "Use pantheon-pack-theologians (M2+) for theologian proxies "
            "(Augustine, al-Ghazali, Nagarjuna, etc.)."
        )
    _DISCLAIMER_ACCEPTED = True


def _ensure_accepted() -> None:
    if not _DISCLAIMER_ACCEPTED:
        raise FoundersPackUnavailable(
            "Call pantheon_pack_founders.accept_disclaimer() before loading. "
            f"Disclaimer:\n\n{DISCLAIMER_TEXT}"
        )


def provide_personas() -> list:
    """Pantheon entry-point hook. Returns nothing until accepted."""
    if not _DISCLAIMER_ACCEPTED:
        return []
    from pantheon.core.persona import load_persona

    out = []
    for name in ("jesus", "muhammad", "buddha"):
        path = _PERSONAS_ROOT / name / "persona.yaml"
        if path.exists():
            out.append(load_persona(path))
    return out


def register() -> int:
    """Register the three founder personas into the global pantheon registry.

    Returns:
        Number of personas registered.
    """
    global _REGISTERED
    _ensure_accepted()
    from pantheon.core.persona import registry

    n = 0
    for p in provide_personas():
        registry.register(p)
        n += 1
    _REGISTERED = True
    return n


# A short string the framework appends to verdicts that include any of
# these personas. The Verdict's `disclaimer` field is augmented with this
# text by the Pantheon coordinator when it sees a founder persona id.
VERDICT_DISCLAIMER = (
    "本 verdict 包含由 LLM 模拟的宗教创始人 persona。模拟为近似，"
    "引文已尽可能 corpus-verified，但不构成任何宗教官方立场或宗教指导。"
    "\n\nThis verdict includes LLM-simulated personas of religious founders. "
    "Outputs are approximate; quotations are corpus-verified where possible "
    "but do not represent any official religious position or constitute "
    "religious guidance."
)


__version__ = "0.1.0a0"
__all__ = [
    "DISCLAIMER_TEXT",
    "FoundersPackUnavailable",
    "VERDICT_DISCLAIMER",
    "accept_disclaimer",
    "provide_personas",
    "register",
]
